### ISSUE TITLE
Compile error in WebConfig

### ISSUE THREAD

**Issue by mikezang** [michael-simons/biking2#2]
When I compile it I got as error as below:
Multiple markers at this line
	- ConfigurableEmbeddedServletContainerFactory cannot be resolved to a type
	- This lambda expression refers to the missing type 
	 ConfigurableEmbeddedServletContainerFactory
	- Line breakpoint:WebConfig [line: 169] - 
	 embeddedServletContainerCustomizer(String, int)

    @Bean
    @Conditional(NeedsCustomizedConnectorCondition.class)
    public EmbeddedServletContainerCustomizer embeddedServletContainerCustomizer(
	    final @Value("${biking2.connector.proxyName}") String proxyName,
	    final @Value("${biking2.connector.proxyPort:80}") int proxyPort
    ) {
	return (ConfigurableEmbeddedServletContainerFactory factory) -> {
	    if (factory instanceof TomcatEmbeddedServletContainerFactory) {
		final TomcatEmbeddedServletContainerFactory containerFactory = (TomcatEmbeddedServletContainerFactory) factory;
		containerFactory.addConnectorCustomizers(connector -> {
		    connector.setProxyName(proxyName);
		    connector.setProxyPort(proxyPort);
		});
	    }
	};
    }

**Comment by michael-simons** [comment]
Hi Mike,

I've just checked myself with a fresh copy:

```
 git clone https://github.com/michael-simons/biking2
 cd biking2/
 mvn clean compile
```

(downloads half the Internet if you didn't do much Spring lately) but i end up with BUILD SUCCESS.

Maybe you're on an old JDK 8?
I'm using

```
java -version
java version "1.8.0_66"
Java(TM) SE Runtime Environment (build 1.8.0_66-b17)
Java HotSpot(TM) 64-Bit Server VM (build 25.66-b17, mixed mode)
```

**Comment by mikezang** [comment]
Hi Michael

I just downloaded your newest copy and installed JRebel, but I still met errors like old version.
You can find there are a lot of errors, by the way, I am on Mac OS 10.9 with Java as below!
But it is very strange, I don't why that I still can compile it and run it with a popup warning! I proceed it then I got that screen what you created! 

Why?  Can you explain for me? I don't like those errors, how can I solve them?

Br
Mike



java version "1.8.0_65"
Java(TM) SE Runtime Environment (build 1.8.0_65-b17)
Java HotSpot(TM) 64-Bit Server VM (build 25.65-b01, mixed mode)

**Comment by michael-simons** [comment]
Sorry, I can't help you. That project works just fine as is. How to you compile it? I don't do support for IDE problems. The project is a maven project. Do you compile it using Maven? And you won't need Jrebel, the plugin does nothing if there's no Jrebel installed.

**Comment by mikezang** [comment]
Well, I am in eclipse, that is ok.
I have another question, after I run it in eclipse, it keeps in localhost:8080, I can use that port for other app, how can I stop it?

Br
Mike

**Comment by michael-simons** [comment]
I've just double checked. It compiles flawless using Maven 3.3.3 as well as Maven 3.2.5 and i guess some older versions as well.

I'm developing with NetBeans (8.1) and i only can recommend it. But anyway, should run in Eclipse or the STS Suite as well.

To get everything straight, i've replaced the JRebel plugin with Spring Boot Devtools, their free and often enough.

Regarding the port: Read the official docs, for example here are all properties that can be configured: https://docs.spring.io/spring-boot/docs/current/reference/html/common-application-properties.html Your searching for "server.port"

I don't know your IDE but the only thing you've gotta do is to stop / kill the Java Process started by the IDE, than the port is free.

**Comment by mikezang** [comment]
Thanks for your advice, I will follow them.

In fact, I found your article because I want to connect to Internet after proxy server!
I checked your source but I am not sure about that usage, does your project can be run only I configed proxyHost and proxyPort?
Tell me more information if you don't mind...

**Comment by michael-simons** [comment]
That project can run as is and behind arbitrary proxies. I close this now.
