### ISSUE TITLE
docs img link 404error

### ISSUE THREAD

**Issue by YaoZihuan** [michael-simons/biking2#3]
please look at this link :https://github.com/michael-simons/biking2/blob/public/src/docs/03_system_scope_and_context.adoc
the images were broken

**Comment by michael-simons** [comment]
Hi,

Those docs are not meant to be rendered by GitHub but instead to be generated by the maven process. See them live at https://biking.michael-simons.eu/docs/index.html#section-system-scope-and-context or generate them after checking out the project. 

Thanks,
Michael.
